Feature/work together section
DarkLordSith/Project_JS_G03 pull request #46
Opened 2024-11-26 14:20 UTC by BohdanKret

add form.js
delete redundant comment reviews.html

2024-11-26 22:55 UTC, DarkLordSith requested changes
All working correct!
Please provide correct styles for modal window and for incorrect email

2024-11-27 08:41 UTC, DarkLordSith requested changes
Please provide styles for incorrect email and button (hover focus)

2024-11-27 11:32 UTC, BohdanKret commented
I corrected color in input, when email has been incorect

2024-11-27 15:41 UTC, DarkLordSith approved these changes

2024-11-27 15:41 UTC, merged